# Generated by Django 4.1.3 on 2022-12-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_alter_entry_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Entrys',
        ),
    ]
