# Generated by Django 4.1.3 on 2022-12-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_rename_entry_entrys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrys',
            new_name='Entry',
        ),
    ]
