# Generated by Django 4.1.3 on 2022-12-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_rename_entrys_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.TextField(),
        ),
    ]
